version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    command: /start
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"

